# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7cb9004754e98c816fdeff7c89d8643b5c192429a0dea7bbc2af6d9b5a88b1c60dbb6e85d08058362fd88553be0552e76f4e12aa2abda61abace24f82a85c992

test:
  secret_key_base: 2e418617ac0b18e600033fa4973fd8a1e1e93d92f0d32300580b661b16ed0c3e82535e4f6398b7e72a7e18496b7a70427a19d290f23aace9886a1530b898542d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
